/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package emila.jacob.pat;

import javax.swing.ImageIcon;

/**
 *
 * @author 24emilaj
 */
public class MenuUI extends javax.swing.JFrame {

    /**
     * Creates new form LandingPage
     */
    public MenuUI() {
        initComponents();
        ImageIcon image = new ImageIcon("C:/Emila PAT/PAT/SVLOGO.jpg");
        lblLogo.setIcon(image);
        this.toolTips();
    }
/**
 * method which sets all the tooltip texts for buttons/textfields on the jframe
 */
    public void toolTips(){
        //sets tooltp text for the log out button
    btnLogOut.setToolTipText("Click this button to exit the program");
    //sets tooltp text for the invoices button
    btnInvoices.setToolTipText("Click this button to see a list of all the invoices");
    //sets tooltp text for the stock ptodduced button
    btnStockProduced.setToolTipText("Click this button to view/edit previous stock or to go insert new stock");
    //sets tooltp text for the capture price button
    btnCapturePrice.setToolTipText("Click this button to go to the page where you can insert a new price");
    //sets tooltp text for the sales analysis button
    btnSalesAnalysis.setToolTipText("Click this button to view the sales analysis");
    //sets tooltp text for the capture order button
    btnCaptureOrder.setToolTipText("Click this button to go to the page where you can log a new order");
    //sets tooltp text for the clients button
    btnClients.setToolTipText("Click this button to view/edit/add to the list of clients");
    //sets tooltp text for the stock projections button
    btnStockProjections.setToolTipText("Click this button to view the stock projections page");
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblMenu = new javax.swing.JLabel();
        btnCaptureOrder = new javax.swing.JButton();
        btnSalesAnalysis = new javax.swing.JButton();
        btnStockProduced = new javax.swing.JButton();
        btnStockProjections = new javax.swing.JButton();
        btnCapturePrice = new javax.swing.JButton();
        btnLogOut = new javax.swing.JButton();
        lblLogo = new javax.swing.JLabel();
        btnClients = new javax.swing.JButton();
        btnInvoices = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblMenu.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        lblMenu.setText("Menu");

        btnCaptureOrder.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnCaptureOrder.setText("Capture Order");
        btnCaptureOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCaptureOrderActionPerformed(evt);
            }
        });

        btnSalesAnalysis.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnSalesAnalysis.setText("Sales Analysis");
        btnSalesAnalysis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalesAnalysisActionPerformed(evt);
            }
        });

        btnStockProduced.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnStockProduced.setText("Stock Produced");
        btnStockProduced.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStockProducedActionPerformed(evt);
            }
        });

        btnStockProjections.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnStockProjections.setText("Stock Projections");
        btnStockProjections.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStockProjectionsActionPerformed(evt);
            }
        });

        btnCapturePrice.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnCapturePrice.setText("Price Adjustments");
        btnCapturePrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCapturePriceActionPerformed(evt);
            }
        });

        btnLogOut.setText("Log Out");
        btnLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogOutActionPerformed(evt);
            }
        });

        btnClients.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnClients.setText("Clients");
        btnClients.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClientsActionPerformed(evt);
            }
        });

        btnInvoices.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnInvoices.setText("Invoices");
        btnInvoices.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInvoicesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(378, 378, 378)
                .addComponent(lblMenu)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnCaptureOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(352, 352, 352))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnInvoices, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(btnStockProjections, javax.swing.GroupLayout.DEFAULT_SIZE, 223, Short.MAX_VALUE)
                                .addComponent(btnStockProduced, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(btnSalesAnalysis, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnCapturePrice, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(btnClients, javax.swing.GroupLayout.DEFAULT_SIZE, 225, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnLogOut)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(27, 27, 27))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblMenu)
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btnLogOut))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnStockProduced, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnStockProjections, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(btnCapturePrice, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(12, 12, 12)
                                        .addComponent(btnSalesAnalysis, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(22, 22, 22)
                                        .addComponent(lblLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(26, 26, 26)
                                .addComponent(btnClients, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 97, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnInvoices, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCaptureOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(92, 92, 92))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

// allows user to view stockproducedui
    private void btnStockProducedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStockProducedActionPerformed
        StockProducedUI sp = new StockProducedUI();
        sp.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_btnStockProducedActionPerformed
// allos user to view captureorderui
    private void btnCaptureOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCaptureOrderActionPerformed
        CaptureOrderUI co = new CaptureOrderUI();
        co.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnCaptureOrderActionPerformed
// allows user to view stockprojectionsui
    private void btnStockProjectionsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStockProjectionsActionPerformed
        StockProjectionsUI sp = new StockProjectionsUI();
        sp.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_btnStockProjectionsActionPerformed
// allows user to view the salesanalysisui 
    private void btnSalesAnalysisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalesAnalysisActionPerformed
        SalesAnalysisUI sa = new SalesAnalysisUI();
        sa.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_btnSalesAnalysisActionPerformed
//allows user to go to a ui where updated prices can be inputted into the database
    private void btnCapturePriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCapturePriceActionPerformed
        CapturePriceUI cp = new CapturePriceUI();
        cp.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_btnCapturePriceActionPerformed
// stops the program from running
    private void btnLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogOutActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnLogOutActionPerformed
// allows user to view the clientsui
    private void btnClientsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClientsActionPerformed
        ClientsUI clients = new ClientsUI();
        clients.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnClientsActionPerformed

    private void btnInvoicesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInvoicesActionPerformed
        InvoicesUI i = new InvoicesUI();
        i.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnInvoicesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCaptureOrder;
    private javax.swing.JButton btnCapturePrice;
    private javax.swing.JButton btnClients;
    private javax.swing.JButton btnInvoices;
    private javax.swing.JButton btnLogOut;
    private javax.swing.JButton btnSalesAnalysis;
    private javax.swing.JButton btnStockProduced;
    private javax.swing.JButton btnStockProjections;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblMenu;
    // End of variables declaration//GEN-END:variables
}
