/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package emila.jacob.pat;

import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author 24emilaj
 */
public class SalesAnalysisUI extends javax.swing.JFrame {

    private ArrayList<salesAnalysis> sales;
    private ArrayList<Client> clients;
    private ArrayList<Invoice> invoices;

    //   private salesAnalysis[] sales;
    /**
     * Creates new form SalesAnalysisUI
     */
    public SalesAnalysisUI() {
        initComponents();
        // DataHandler dh = new DataHandler();
        this.insertTable();
        //    this.addTable();
        this.toolTips();

    }
    
    public void toolTips(){
    btnBack.setToolTipText("Click this button to return to the menu");
    
    }

    public void testPrintDeleteMe() {
        for (int i = 0; i < sales.size(); i++) {
            System.out.print(sales.get(i));
        }
    }
//stackoverflow

    private void insertTable() {
        DataHandler dh = new DataHandler();
        /*ArrayList<salesAnalysis>*/ sales = dh.sales();
//        invoices = dh.getAllInvoices();
//        clients = dh.getAllClients();
        //testPrintDeleteMe();
        
//        double totalIncome = 0;
        //income = 

        DefaultTableModel dtm = (DefaultTableModel) tblSales.getModel();
        tblSales.setModel(dtm);
        Object sale[] = new Object[3];
        for (int i = 0; i < sales.size(); i++) {
            sale[0] = "" + sales.get(i).getClientName();
          //  sale[1] = "" + Double.parseDouble("" + Math.round((sales.get(i).getTotalIncome())*100)/100);
          sale[1] = "" + (sales.get(i).getTotalIncome());
//            for (int j = 0; j < invoices.size(); j++) {
//                if (invoices.get(i).getClientID() == clients.get(i).getClientID() && sales.get(i).getClientName().equalsIgnoreCase(sales.get(i).getClientName())) {
//                    numOrders++;
//                }
//            }
//            System.out.println(numOrders);
//       //
            sale[2] = "" + sales.get(i).getNumOrders();
            dtm.addRow(sale);
//            for (int j = 0; j < dh.getAllInvoices().size(); j++) {
//                if (sales.get(i).getInvoiceID() == sales.get(j).getInvoiceID()) {
//                    numOrders++;
//                    //   System.out.println(numOrders);
//                    if (sales.get(i).getClientName().equalsIgnoreCase(sales.get(j).getClientName()) && sales.get(i).getDiscountPercentage() > 0) {
//                        totalIncome = sales.get(i).getPrice() * sales.get(i).getQuantity() * (sales.get(i).getDiscountPercentage()) / 100;
//
//                    } else {
//                        if (("" + sales.get(i).getDiscountPercentage()).equalsIgnoreCase(null) && sales.get(i).getClientName().equalsIgnoreCase(sales.get(j).getClientName())) {
//                            totalIncome = sales.get(i).getQuantity() * sales.get(i).getPrice();
//                            //     System.out.println(totalIncome);
//                        }
//                    }
//                }

//            this.add(tblSales);
//            tblSales.setVisible(true);
        }
        tblSales.setRowSelectionInterval(0, 0);
    }
//
//    public void addTable() {
//        JTable tblSales = new JTable();
//        JScrollPane spTable = new JScrollPane(tblSales);
//        JPanel panel = new JPanel();
//
//        panel.add(spTable);
//
//    }

    //JScrollPane spTable = new JScrollPane(table);
//JPanel panel = new JPanel();
//panel.add(spTable);
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnHelp = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblSales = new javax.swing.JTable();
        btnBack = new javax.swing.JButton();

        btnHelp.setText("Help");
        btnHelp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHelpActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Sales Analysis");

        jLabel2.setText("Client Loyalty Ranking");

        tblSales.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "clientname", "totalIncome", "numOrders"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblSales);

        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1)))
                .addContainerGap(239, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(30, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnBack)
                        .addGap(19, 306, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addComponent(btnBack)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        MenuUI m = new MenuUI();
        m.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnHelpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHelpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnHelpActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SalesAnalysisUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SalesAnalysisUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SalesAnalysisUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SalesAnalysisUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SalesAnalysisUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnHelp;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblSales;
    // End of variables declaration//GEN-END:variables
}
